version: 2
project_name: gitresume-cli

before:
  hooks:
    # Build your React frontend before GoReleaser builds binaries
    - echo "Building React app..."
    - cd internal/server/web && bun run build

builds:
  - id: gitresume
    main: ./main.go
    binary: gitresume

    # enable CGO and custom compilers per target
    env:
      - CGO_ENABLED=1

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Skip ARM64 targets without proper cross-compiler setup
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

    flags:
      - -tags=sqlite

    ldflags:
      - "-s -w -X main.version={{.Version}}"

    # overrides per OS to use proper compiler
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-musl-gcc
        ldflags:
          - "-s -w -linkmode external -extldflags '-static' -X main.version={{.Version}}"
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: iamhabbeboy
    name: gitresume-cli
  prerelease: auto

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# 🧱 Homebrew Formula
brews:
  - name: gitresume
    repository:
      owner: iamhabbeboy
      name: homebrew-tap
    commit_author:
      name: Abiodun Azeez
      email: iamhabbeboy@gmail.com
    directory: Formula
    homepage: "https://gitresume.app"
    description: "A CLI tool that converts your git commit history into resume-ready bullet points using AI."
    license: MIT
    test: |
      system "#{bin}/gitresume --version"
    install: |
      bin.install "gitresume"

# 🧱 Chocolatey Package
# chocolateys:
#   - name: gitresume
#     owners: iamhabbeboy
#     title: "gitresume"
#     summary: "Generate resume bullet points from your Git commit history using AI"
#     description: "gitresume is a Go-based CLI tool that helps developers turn Git commits into professional resume content."
#     project_url: "https://github.com/iamhabbeboy/gitresume-cli"
#     license_url: "https://github.com/iamhabbeboy/gitresume-cli/blob/main/LICENSE"
#     authors: "Abiodun Azeez"
#     tags: "go cli resume git"
#     api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
#     source_repo: "https://github.com/iamhabbeboy/gitresume-cli"