version: 2
project_name: gitresume-cli

before:
  hooks:
    # Build your React frontend before GoReleaser builds binaries
    - echo "Building React app..."
    - cd internal/server/web && bun run build

builds:
  - id: gitresume
    main: ./main.go
    binary: gitresume

    # enable CGO and custom compilers per target
    env:
      - CGO_ENABLED=1

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Skip ARM64 targets without proper cross-compiler setup
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

    flags:
      - -tags=sqlite

    ldflags:
      - "-s -w -X main.version={{.Version}}"

    # overrides per OS to use proper compiler
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-musl-gcc
        ldflags:
          - "-s -w -linkmode external -extldflags '-static' -X main.version={{.Version}}"
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: iamhabbeboy
    name: gitresume-cli
  prerelease: auto

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# 🧱 Homebrew Formula
brews:
  - name: gitresume
    repository:
      owner: iamhabbeboy
      name: homebrew-tap
    commit_author:
      name: Abiodun Azeez
      email: iamhabbeboy@gmail.com
    directory: Formula
    homepage: "https://gitresume.app"
    description: "A Resume builder CLI tool that converts your git commit history into resume-ready bullet points using AI."
    license: MIT
    test: |
      system "#{bin}/gitresume --version"
    install: |
      bin.install "gitresume"
      
publishers:
  - name: chocolatey
    cmd: |
      echo "🏗️ Packaging Windows build for Chocolatey..."

      # Locate the Windows build output directory
      WIN_DIR=$(find dist -type d -name "*_windows_*" | head -n 1)
      if [ -z "$WIN_DIR" ]; then
        echo "⚠️ No Windows artifact found. Skipping Chocolatey publishing."
        exit 0
      fi

      mkdir -p dist/choco
      cp "$WIN_DIR/gitresume-cli.exe" dist/choco/

      echo "📦 Creating nuspec..."
      cat > dist/choco/gitresume.nuspec <<'EOF'
      <?xml version="1.0"?>
      <package>
        <metadata>
          <id>gitresume-cli</id>
          <version>{{ .Version }}</version>
          <authors>Abiodun Azeez</authors>
          <owners>Abiodun Azeez</owners>
          <projectUrl>https://gitresume.app</projectUrl>
          <licenseUrl>https://github.com/iamhabbeboy/gitresume/blob/main/LICENSE</licenseUrl>
          <requireLicenseAcceptance>false</requireLicenseAcceptance>
          <summary>CLI tool that converts git commit history into resume-ready bullet points using AI.</summary>
          <description>GitResume transforms your git commit history into resume-ready bullet points.</description>
          <tags>cli git ai resume</tags>
        </metadata>
        <files>
          <file src="gitresume-cli.exe" target="tools" />
        </files>
      </package>
      EOF

      echo "📦 Packing .nupkg..."
      cd dist/choco
      zip -r "gitresume-cli.{{ .Version }}.nupkg" gitresume.nuspec gitresume-cli.exe

      echo "🚀 Uploading to Chocolatey..."
      if [ -z "{{ .Env.CHOCOLATEY_API_KEY }}" ]; then
        echo "❌ CHOCOLATEY_API_KEY not set. Skipping upload."
        exit 0
      fi

      curl -X PUT "https://push.chocolatey.org/api/v2/package" \
        -H "X-NuGet-ApiKey: {{ .Env.CHOCOLATEY_API_KEY }}" \
        --data-binary "@gitresume-cli.{{ .Version }}.nupkg"

      echo "✅ Windows package uploaded to Chocolatey!"