version: 2
project_name: gitresume-cli

before:
  hooks:
    # Build your React frontend before GoReleaser builds binaries
    - echo "Building React app..."
    - cd internal/server/web && bun run build

builds:
  - id: gitresume
    main: ./main.go
    binary: gitresume

    # enable CGO and custom compilers per target
    env:
      - CGO_ENABLED=1

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Skip ARM64 targets without proper cross-compiler setup
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

    flags:
      - -tags=sqlite

    ldflags:
      - "-s -w -X main.version={{.Version}}"

    # overrides per OS to use proper compiler
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-musl-gcc
        ldflags:
          - "-s -w -linkmode external -extldflags '-static' -X main.version={{.Version}}"
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: iamhabbeboy
    name: gitresume-cli
  prerelease: auto

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# 🧱 Homebrew Formula
brews:
  - name: gitresume
    repository:
      owner: iamhabbeboy
      name: homebrew-tap
    commit_author:
      name: Abiodun Azeez
      email: iamhabbeboy@gmail.com
    directory: Formula
    homepage: "https://gitresume.app"
    description: "A CLI tool that converts your git commit history into resume-ready bullet points using AI."
    license: MIT
    test: |
      system "#{bin}/gitresume --version"
    install: |
      bin.install "gitresume"

publishers:
  - name: chocolatey
    cmd: |
      echo "Packaging Chocolatey .nupkg on macOS..."
      mkdir -p dist/choco
      cp dist/gitresume_*_windows_amd64/gitresume.exe dist/choco/
      cat > dist/choco/gitresume.nuspec <<'EOF'
      <?xml version="1.0"?>
      <package>
        <metadata>
          <id>gitresume</id>
          <version>{{ .Version }}</version>
          <authors>Abiodun Azeez</authors>
          <owners>Abiodun Azeez</owners>
          <projectUrl>https://gitresume.app</projectUrl>
          <licenseUrl>https://github.com/iamhabbeboy/gitresume/blob/main/LICENSE</licenseUrl>
          <requireLicenseAcceptance>false</requireLicenseAcceptance>
          <summary>CLI tool that converts git commit history into resume-ready bullet points using AI.</summary>
          <description>GitResume transforms your git commit history into resume-ready bullet points.</description>
          <tags>cli git ai resume</tags>
        </metadata>
        <files>
          <file src="gitresume.exe" target="tools" />
        </files>
      </package>
      EOF
      cd dist/choco && zip -r gitresume.{{ .Version }}.nupkg gitresume.nuspec gitresume.exe
      echo "Uploading to Chocolatey..."
      curl -X PUT "https://push.chocolatey.org/api/v2/package" \
        -H "X-NuGet-ApiKey: {{ .Env.CHOCOLATEY_API_KEY }}" \
        --data-binary "@gitresume.{{ .Version }}.nupkg"